language: go

go:
  - 1.5
  - 1.6
  - tip

matrix:
  allow_failures:
    - go: tip
    - env: "GO15VENDOREXPERIMENT=1; UPDATE_DEPS=1"

env:
  matrix:
    - "GO15VENDOREXPERIMENT=1; UPDATE_DEPS=0"
    - "GO15VENDOREXPERIMENT=1; UPDATE_DEPS=1"
